In [23]:
##Q1  Discuss string slicing and provide examples 

'''
String is a sequence of charecter, it represent and manipulate textual data.

'''
string1 = 'I am a good student'  ##here if need to print only "I am good"

string1[0:11] ## positive indexing

string1[:-8] ## negetive indexing

string1[0:11:3] ## positive indexing with step

string1[::-1] ## right to left direction

'tneduts doog a ma I'

In [103]:
##Q2 Explain the key features of lists in Python

'''
List are ordered collection of items, list are mutables, item assignment possible

'''
## key feature of list
## insert new element in to list
home_work = ['module1', 'module2', 'module3']
home_work.insert(3, 'module4')

##extend a another list to current list
home_work1 = ['module1', 'module2', 'module3']
home_work2 = ['module4', 'module5', 'module6']
home_work1.extend(home_work2)

## concatnate different list in to a single list

home_work1 = ['module1', 'module2', 'module3']
home_work2 = ['module4', 'module5', 'module6']
home_work3 = ['module7', 'module8', 'module9']

weekly_Assignment = home_work1 + home_work2 + home_work3

## repete list element operation

module = 'this is module'

for i in range(0, 5):
    print(f'{module} - {i}')

##membership 

home_work = ['module1', 'module2', 'module3']

'module1' in home_work ## value true

## shallow copy

home_work1 = ['module1', 'module2', 'module3']
home_work2 = ['module4', 'module5', 'module6']

home_work2 = home_work1 ## home_work1 and home_work2 having same value
home_work2[1] = 'module8' ##in shallow copy if in home_work2 any element value changed, autometically the home_work1 memory also effect the same.

print(home_work1)

## deep copy

home_work3 = ['module1', 'module2', 'module3']
home_work4 = home_work3.copy()

home_work4[0] ='module4'

print(home_work3)
print(home_work4)

##list sorting

home_work5 = ['module7', 'module2', 'module5', 'module1', 'module3', 'module8' , 'module4', 'module6']

sorted(home_work5)

## to find the index of any element

home_work5 = ['module7', 'module2', 'module5', 'module1', 'module3', 'module8' , 'module4', 'module6']

home_work5.index('module3')


## to find length of an element

len(home_work5)

## to remove element from list
home_work5.remove('module6') ## remove specific element from list
home_work5.pop() ## by default the last element in the list will display and delete from list after. 
home_work5.clear() ## list is empty
del home_work5  ## the veriable home_work5 itself no longer available


## list comprehension 
Akhshya_kumar = ['10', '200', '3000', '40000', '500000' ]
Rajpal_yadav = []

## the for loop is in complicated lengthy way

for i in Akhshya_kumar:
    Rajpal_yadav.append(i*2)
print('woo-hoo !! paisa hi paisa', Rajpal_yadav)

## this is in compheresive way

[Akhshya_kumar * 2 for Akhshya_kumar in Rajpal_yadav]

this is module - 0
this is module - 1
this is module - 2
this is module - 3
this is module - 4
['module1', 'module8', 'module3']
['module1', 'module2', 'module3']
['module4', 'module2', 'module3']
woo-hoo !! paisa hi paisa ['1010', '200200', '30003000', '4000040000', '500000500000']

['10101010',
 '200200200200',
 '3000300030003000',
 '40000400004000040000',
 '500000500000500000500000']

In [46]:
##Q3 Describe how to access, modify, and delete elements in a list with examples.

list_container = ['list1', 'list2', 'list3', 'list4', 1, 20, 300, 4000, 5.2]

list_container[1] ## access the element using index 1
list_container[3] = 10
list_container.pop(7) # this is a way
list_container.remove('list3') ## this is another way

In [ ]:
##Q4 Compare contrast tuples and lists with examples

                   ##Tuple                                                                List
'''    
1. represent in simple bracket ex: (1, 2, 3)                                  1. represent in squre bracket ex: [1, 2, 3]
2. tuples are immutable and hetrogeneous, not support item assignment         2. list are mutable, item assignment is support
3. we use tuples where the element do not want to modify the data.            3. list is nothing but an shopping_cart where anything can be stored.
   example: adhar card, bank account number, employee ID                         we can add, remove and modify the data in list
4. tuple1= ('hello', 'world', 1, 2, 1, 2, 3, 1, 2, 3, 4)                      4. newlist = ['hello', True, 3+5j, 1, 2, 3.4]
   output is ('hello', 'world', 1, 2,3,4) ## because tuples are                  newlist.append('world')
   also are ordered collection of elements.                                       newlist.remove('world')
                                                                                 newlist[2] = str('world')
'''

In [85]:
##Q5 Describe the key features of sets and provide examples of their use

'''
-> sets are un-ordered and unique collection of elements, it does not allow duplicate elements
-> in set indexing not possible
-> sets are representing inside the curly bracket {1,2, 'somesh'}
'''
newset = {1, 1, 2, 1, 2, 3, 1, 2, 3, 4, 'somesh', 'hello', 'world' }
type(newset)
print(newset)

## converting a list in to set
newlist = [1, 1, 2, 1, 2, 3, 1, 2, 3, 4, 'somesh', 'hello', 'world' ]

convert_set = set(newlist)
type(convert_set)

convert_list = list(convert_set)
type(convert_list)

## to remove any element from set we can use pop(), but it remove randomly some element
remove_set = newset.pop()
print(remove_set)

## for specific element to remove

newlist.remove('somesh')
print(newlist)

other_set = { 'somesh', 'somesh', 'dash', 1,2,1,2,3, 1,2,3,4}
other_set.update('deepankar') ## here elements get in to add in a unique way
other_set.update(['deepankar']) ## here the list of element get add together

## set operation
'''
there are four set operation

setA = {1, 2, 3}
setB = {3, 4, 5}

1. union set 
 -> it represent setA | setB, all the set element included here
  
 setA = {1, 2, 3}
 setB = {3, 4, 5}

 uninon set is {1, 2, 3, 4, 5}

2.intersection set
 -> it represent setA & setB, common element are in this set
 
 setA = {1, 2, 3}
 setB = {3, 4, 5}

 intersection set is { 3 }

3.difference set
 -> it represent setA - setB , the element which is available in first set, not in second set
 
  setA = {1, 2, 3}
  setB = {3, 4, 5}

  intersection set is { 1, 3 }

4.symentric difference set
 -> it represent setA ^ setB, all the element excluding the common element

 setA = {1, 2, 3}
 setB = {3, 4, 5}

 intersection set is { 1, 2, 4, 5 }

'''

{1, 2, 3, 4, 'somesh', 'world', 'hello'}
1
[1, 1, 2, 1, 2, 3, 1, 2, 3, 4, 'hello', 'world']

'\nthere are four set operation\n\nsetA = {1, 2, 3}\nsetB = {3, 4, 5}\n\n1. union set \n -> it represent setA | setB, all the set element included here\n  \n setA = {1, 2, 3}\n setB = {3, 4, 5}\n\n uninon set is {1, 2, 3, 4, 5}\n\n2.intersection set\n -> it represent setA & setB, common element are in this set\n \n setA = {1, 2, 3}\n setB = {3, 4, 5}\n\n intersection set is { 3 }\n\n3.difference set\n -> it represent setA - setB , the element which is available in first set, not in second set\n \n  setA = {1, 2, 3}\n  setB = {3, 4, 5}\n\n  intersection set is { 1, 3 }\n\n4.symentric difference set\n -> it represent setA ^ setB, all the element excluding the common element\n\n setA = {1, 2, 3}\n setB = {3, 4, 5}\n\n intersection set is { 1, 2, 4, 5 }\n\n'

In [101]:
##Q6  Discuss the use cases of tuples and sets in Python programming

## use cases of tuple in python
#-------------------------------

New_tuple = (1,2,3, 'hello', 'world', 1.1, 1, 2 )

New_tuple.count(1)

New_tuple.index(2) ## firs index occurance

other_tuple = (1,2,3, 'hello', 'world', 1.1, 1, 2 )

update_tuple = New_tuple + other_tuple


## use cases of set in python
#-----------------------------

newset = {1, 1, 2, 1, 2, 3, 1, 2, 3, 4, 'somesh', 'hello', 'world' }
type(newset)
print(newset)

## converting a list in to set
newlist = [1, 1, 2, 1, 2, 3, 1, 2, 3, 4, 'somesh', 'hello', 'world' ]

convert_set = set(newlist)
type(convert_set)

convert_list = list(convert_set)
type(convert_list)

## to remove any element from set we can use pop(), but it remove randomly some element
remove_set = newset.pop()
print(remove_set)

## for specific element to remove

newlist.remove('somesh')
print(newlist)

other_set = { 'somesh', 'somesh', 'dash', 1,2,1,2,3, 1,2,3,4}
other_set.update('deepankar') ## here elements get in to add in a unique way
other_set.update(['deepankar']) ## here the list of element get add together

## set operation
'''
there are four set operation

setA = {1, 2, 3}
setB = {3, 4, 5}

1. union set 
 -> it represent setA | setB, all the set element included here
  
 setA = {1, 2, 3}
 setB = {3, 4, 5}

 uninon set is {1, 2, 3, 4, 5}

2.intersection set
 -> it represent setA & setB, common element are in this set
 
 setA = {1, 2, 3}
 setB = {3, 4, 5}

 intersection set is { 3 }

3.difference set
 -> it represent setA - setB , the element which is available in first set, not in second set
 
  setA = {1, 2, 3}
  setB = {3, 4, 5}

  intersection set is { 1, 3 }

4.symentric difference set
 -> it represent setA ^ setB, all the element excluding the common element

 setA = {1, 2, 3}
 setB = {3, 4, 5}

 intersection set is { 1, 2, 4, 5 }

'''

In [119]:
##Q7  Describe how to add, modify, and delete items in a dictionary with examples

'''
 -> Dictionary is a type of data structure which stores data in key pair
'''

My_dictionary = {'First name': 'Somesh', 'last name': 'Dash', 'Age': 28, 'course': 'Data science', 'duration': 6 }
 
My_dictionary['institution'] = 'Physical wallah skills' ## to add a key element index with its element value 

My_dictionary['Age'] = 29 ## to modify the key element index to a new element value 

del My_dictionary['duration'] ## Delete the key with its value from the dictionary

In [134]:
##Q8  Discuss the importance of dictionary keys being immutable and provide examples

'''
dictionary stores the data in key pair, here no indexing available, in place of indexing key are help to access the value. these key are unique and immutable

My_dictionary = {'First name': 'Somesh', 'last name': 'Dash', 'Age': 28, 'course': 'Data science', 'duration': 6 }

My_dictionary['First name']

My_dictionary['First name'] = (0, 1, 3)

My_dictionary.keys() check all the key 

My_dictionary.values() check all the values

'''